name: eais
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.4
  - cloudpickle=3.1.1
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - double-conversion=3.3.1
  - expat=2.7.0
  - farama-notifications=0.0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - freetype=2.13.3
  - graphite2=1.3.13
  - gymnasium=0.29.1
  - harfbuzz=11.1.0
  - icu=75.1
  - jax-jumpy=1.0.0
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.3
  - libclang13=20.1.3
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm20=20.1.3
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.1
  - libxml2=2.13.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - munkres=1.1.4
  - mysql-common=9.2.0
  - mysql-libs=9.2.0
  - ncurses=6.5
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=25.0
  - pcre2=10.44
  - pip=25.0.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - qhull=2020.2
  - qt6-main=6.9.0
  - readline=8.2
  - scikit-fmm=2025.1.29
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=78.1.1
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.4.2
  - typing_extensions=4.13.2
  - unicodedata2=16.0.0
  - wayland=1.23.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - args==0.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chex==0.1.89
      - clint==0.5.1
      - decorator==5.2.1
      - etils==1.12.2
      - filelock==3.13.1
      - flax==0.10.5
      - fsspec==2025.3.2
      - hj-reachability==0.7.0
      - humanize==4.12.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - jax==0.6.0
      - jaxlib==0.6.0
      - jinja2==3.1.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - moviepy==2.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.12
      - pandas==2.2.3
      - pillow==10.4.0
      - posggym==0.6.0.dev1
      - proglog==0.1.11
      - protobuf==6.30.2
      - pycparser==2.22
      - pygame==2.6.1
      - pygments==2.19.1
      - pymunk==6.11.1
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==14.0.0
      - seaborn==0.13.2
      - simplejson==3.20.1
      - sympy==1.13.1
      - tensorstore==0.1.73
      - toolz==1.0.0
      - torch==2.6.0+cu126
      - tqdm==4.67.1
      - treescope==0.1.9
      - triton==3.2.0
      - types-requests==2.32.0.20250328
      - tzdata==2025.2
      - urllib3==2.4.0
      - zipp==3.21.0
